ALTER TABLE evaluation_score
DROP CONSTRAINT unique_skill_per_eval_per_algo;

ALTER TABLE evaluation_score
ADD CONSTRAINT one_skill_per_algo_per_eval_per_process
UNIQUE (evaluation_id,skill_id,scoring_algo_version,process_type);
